lab/MidTermJSF/src/java/edu/mum/cs545/midterm/bean/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mum.cs545.midterm.bean;

import javax.inject.Named;
import javax.enterprise.context.RequestScoped;

/**
 *
 * @author sam
 */
@Named(value = "loginBean")
@RequestScoped
public class LoginBean {
    private String username;
    private String password;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    /**
     * Creates a new instance of LoginBean
     */
    public LoginBean() {
    }
    
}

lab/MidTermJSF/src/java/edu/mum/cs545/midterm/model/Login.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mum.cs545.midterm.model;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author sam
 */
public class Login {

    private List<Person> people = new ArrayList<>();

    public Login(){
        createAccounts();
    }
    
    // login return person object instead of boolean use to store login user
    public Person login(String username, String password) {
        for (Person person : people) {
            if(person.getUserName().equalsIgnoreCase(username) && 
               person.getPassword().equals(password))
                return person;
        }
        return null;
    }    

    public List<Person> getAccounts() {
        return people;
    }

    public boolean createAccounts() {
        people = new ArrayList<>();
        people.add(new Person("Jack", "jack", "apple", true));
        people.add(new Person("Jill", "jill", "rose", false));
        people.add(new Person("John", "john", "car", false));
        people.add(new Person("Jim", "jim", "house", false));
        people.add(new Person("Jane", "jane", "diamond", false));
        people.add(new Person("Jordan", "jo", "ball", false));
        people.add(new Person("Jasmin", "jas", "jazz", false));
        people.add(new Person("Sam", "sammy", "123456", true));
        return true;
    }
}

lab/MidTermJSF/src/java/edu/mum/cs545/midterm/managedbean/ProductMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mum.cs545.midterm.managedbean;

import edu.mum.cs545.midterm.bean.ProductBean;
import edu.mum.cs545.midterm.model.Product;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.TreeMap;
import javax.inject.Named;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

/**
 *
 * @author sam
 */
@Named(value = "productMB")
@ApplicationScoped
public class ProductMB {
    @Inject
    private ProductBean productBean;
    private TreeMap<Integer, Product> products = new TreeMap<>();

    public ProductBean getProductBean() {
        return productBean;
    }

    public void setProductBean(ProductBean productBean) {
        this.productBean = productBean;
    }

    public TreeMap<Integer, Product> getProducts() {
        return products;
    }

    public void setProducts(TreeMap<Integer, Product> product) {
        this.products = product;
    }
    public List<Product> getProductList(){
        if(products.size()>0)
            return new ArrayList<>(products.values());
        else
            return new ArrayList<>();
    }
    /**
     * Creates a new instance of ProductMB
     */
    public ProductMB() {
    }
    
    public String addProduct() {
        int productId = 0;
        try {
            productId = products.lastKey();
        } catch (NoSuchElementException e) {

        }
        Product product=new Product(++productId,productBean.getName(),productBean.getPrice(),productBean.getDescription());
        products.put(productId, product);
        return "home?faces-redirect=true";
    }
    public String editProduct(int id) {
        Product product=products.get(id);
        productBean.setId(product.getId());
        productBean.setName(product.getName());
        productBean.setPrice(product.getPrice());
        productBean.setDescription(product.getDescription());
        return "edit?faces-redirect=true";
    }

    public String saveProduct() {
        products.put(productBean.getId(), new Product(productBean.getId(),productBean.getName(),productBean.getPrice(),productBean.getDescription()));
        return "view?faces-redirect=true";
    }
    
    public String deleteProduct(int id) {
        products.remove(id);
        return "view?faces-redirect=true";
    }
    
    public void clearProductBean(){
        productBean.setId(0);
        productBean.setName("");
        productBean.setPrice(0);
        productBean.setDescription("");
    }
    public String newProductPage(){
        clearProductBean();
        return "add?faces-redirect=true";
    }
}

lab/MidTermJSF/web/404.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <p style="text-align: center">Oops it looks like the page you requested has disappeared.</p>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>        
    </h:body>
</html>

lab/MidTermJSF/web/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <ui:composition template="/templates/product.xhtml">
            <ui:define name="mode">
                Enter new 
            </ui:define>
            <ui:define name="button">
                <h:commandButton value="Add" action="#{productMB.addProduct()}"/>
                <h:commandButton value="Cancel" action="home?face-redirect=true" immediate="true" />
            </ui:define>
        </ui:composition>           
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <ui:composition template="/templates/product.xhtml">
            <ui:define name="mode">
                Modify
            </ui:define>
            <ui:define name="button">
                <h:commandButton value="Modify" action="#{productMB.saveProduct()}"/>
                <h:commandButton value="Cancel" action="view?face-redirect=true" immediate="true" />
            </ui:define>
        </ui:composition>           
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <p style="text-align: center">It looks like something broke :S</p>
            <p style="text-align: center">Please contact our technical support at</p>
            <p style="text-align: center">support@cs545.edu</p>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <ui:insert name="header">
                <ui:include src="/templates/header.xhtml"/>
            </ui:insert>
            Please select action to perform:<br/>

            <br/>
            <h:button value="View List" outcome="view"/>
            <h:form>
                <h:commandButton value="Add" action="#{productMB.newProductPage()}" rendered="#{loginMB.loginUser.admin}"/>
            </h:form>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <h1 style="text-align: center">This is the Midterm Programming Exam</h1>
            To start the web-application please click start.<br/>
            The number of users currently logged in is : ${applicationMB.sessionCount}<br/>
            <br/>
            <h:button value="Start" outcome="login"/>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <h1>Please log in to continue</h1>
            <h:form>
                <table>
                    <tr>
                        <td>User Name:</td>
                        <td>
                            <h:inputText id="username" value="#{loginMB.loginBean.username}"
                                         validatorMessage="#{msgs.usernameValidate}">
                                <f:validateRequired />
                            </h:inputText>                        
                            <h:message for="username" style="color:red"/>
                        </td>
                    </tr>
                    <tr>
                        <td>Password:</td>
                        <td>
                            <h:inputSecret id="password" value="#{loginMB.loginBean.password}"
                                           validatorMessage="#{msgs.passwordValidate}">
                                <f:validateRequired />
                            </h:inputSecret>                        
                            <h:message for="password" style="color:red"/>
                        </td>
                    </tr>
                </table>
                <h:commandButton action="#{loginMB.login()}" value="Login"/>
                <!-- Global messages -->
                <h:messages style="color:red" globalOnly="true" />
            </h:form>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/redirect.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <div>
            Sorry, you are not authorized to view this page<br/>
            Please login first<br/>
            <h:button value="Go to login page" outcome="login"/>            
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
            
        </div>
    </h:body>
</html>

lab/MidTermJSF/web/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <div>
            <ui:insert name="header">
                <ui:include src="/templates/header.xhtml"/>
            </ui:insert>
            The list of products in our system are:<br/>

            <h:dataTable border="1" value="#{productMB.productList}" var="product">
                <h:column>
                    <f:facet name="header" >ID</f:facet>
                        #{product.id}
                </h:column>
                <h:column>
                    <f:facet name="header" >Name</f:facet>
                        #{product.name}
                </h:column>
                <h:column>
                    <f:facet name="header" >Price</f:facet>
                    $#{product.price}
                </h:column>
                <h:column>
                    <f:facet name="header" >Description</f:facet>
                        #{product.description}
                </h:column>
                <h:column>
                    <f:facet name="header" >Edit Link</f:facet>
                    <h:form>
                        <h:commandLink action="#{productMB.editProduct(product.id)}" value="Edit"/>
                    </h:form>                    
                </h:column>
                <h:column>
                    <f:facet name="header" >Delete Link</f:facet>
                    <h:form>
                        <h:commandLink action="#{productMB.deleteProduct(product.id)}" value="Delete" onclick="return confirm('Are you sure you want to delete this student?')"/>
                    </h:form>                    
                </h:column>
            </h:dataTable>
            <br/>
            <h:button outcome="home" value="Done"></h:button>
            <ui:insert name="footer">
                <ui:include src="/templates/footer.xhtml"/>
            </ui:insert>
        </div>
    </h:body>
</html>